apiVersion: batch/v1
kind: CronJob
metadata:
  name: test-cronjob
spec: #CronJob
  schedule: "* * * * *"
  jobTemplate:
    spec: #Job
      template:
        spec: #Pod
          containers:
          - name: long-job
            image: python 
            command: ["python"]
            args: ["-c", "import time; print('starting'); time.sleep(30); print('done')"]
          restartPolicy: Never
      backoffLimit: 2