# Deployment
apiVersion: v1
kind: Deployment
metadata: 
  name: webapp
spec:
  replicas: 2 # for frontend min 2 replica on diffrent nodes
  #########################PODS#################################
  template: # pod definiton
    metadata:
      name: webapp
      labels:
        app: webapp # Label for service
     ###########################CONTAINERS#######################   
    spec:
      containers:
      - name: webapp
        image: richardchesterwood/k8s-fleetman-webapp-angular:release0

