# First Release
apiVersion: v1
kind: Pod
metadata:
  name: webapp
  labels:
    app: webapp # Label for service
    release: "0"
spec:
  containers:
  - name: webapp
    image: richardchesterwood/k8s-fleetman-webapp-angular:release0

--- 
# Second Release
apiVersion: v1
kind: Pod
metadata:
  name: webapp-release-0-5
  labels:
    app: webapp # Label for service
    release: "0-5" 
spec:
  containers:
  - name: webapp
    image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5

