# Queue microservice
apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue
spec:
  selector:
    matchLabels:
      app: queue
  replicas: 1
  template: 
    metadata:
      labels:
        app: queue
    spec:
      containers:
      - name: queue
        image: richardchesterwood/k8s-fleetman-queue:release1
        resources:
          requests:
            memory: 300Mi # 300mb
            cpu: 100m # 0.1CPU
          limits:
           memory:
           cpu: 


