
groups:
  - name: my-rules
    rules:
    # Dane zagregowane 
    - record: job:node_cpu_seconds:avg_idle
      expr: avg without(cpu)(rate(node_cpu_seconds_total{mode="idle"}[5m]))
    # Alert
    - alert: NodeExporterDown
      expr: up{job="node_exporter"} == 0