apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
spec:
  containers:
  - name: mycontainer
    image: redis
    env:
      - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: username
            optional: false
      - name: SECRET_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: password
            optional: false
  restartPolicy: Never


# kubectl create -f readsecret.yaml
# kubectl get pod

# [ Login to Pod echo print variables - sprawdzenie czy mamy dostęp do secrets z pliku]
# kubectl exec --stdin --tty secret-env-pod -- /bin/bash

# [usunięcie pliku secret]
# kubectl delete secret <secret-name> --namespace <namespace-name>
