apiVersion: v1
kind: Pod
metadata:
  name: configmap-demo-pod
spec:
  containers:
    - name: demo
      image: alpine
      command: ["sleep", "3600"]
      env:
        - name: PLAYER_INITIAL_LIVES # capital letter
          valueFrom:
            configMapKeyRef:
              name: game-demo           # name of config map
              key: player_initial_lives # vulue for key
        - name: UI_PROPERTIES_FILE_NAME
          valueFrom:
            configMapKeyRef:
              name: game-demo
              key: ui_properties_file_name
      volumeMounts:
      - name: config # the same name
        mountPath: "/config"
        readOnly: true
  volumes:
  - name: config # the same name
    configMap:
      name: game-demo # name of config map
      items:
      - key: "game.properties"
        path: "game.properties"
      - key: "user-interface.properties"
        path: "user-interface.properties"
